@endpoint = http://localhost:3000/graphql


#& ---------------------------- ALL RESTAURANTS
### 
POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query getAllRestaurants {
    getAllRestaurants {
        name
        description
        cookingStyles {
            label
        }
    }
}

#& ---------------------------- RESTAURANT BY ID
### 
POST {{ endpoint }}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query getRestaurant($id:ID!) {
    getRestaurant(id: $id) {
        name
        description
        cookingStyles {
            label
        }
    }
}

{"id":1}

#& ---------------------------- ALL RESTAURANTS BY COOKING STYLES LABEL
### 
POST {{ endpoint }}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query getRestaurantByCookingStyle($label: String!) {
    getRestaurantByCookingStyle(label: $label){
        name
    }
}

{"label": "Suisse"}

#& ---------------------------- ALL MANAGERS
###
POST {{ endpoint }}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query getAllManagers {
     getAllManagers {
        firstname
        lastname
        email
    }
}

#& ---------------------------- MANAGER BY ID
### 
POST {{ endpoint }}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query getManager($id: ID!) {
     getManager(id: $id) {
        firstname
        lastname
        email
    }
}

{"id":3}

#& ---------------------------- ALL CITIES
### 
POST {{ endpoint }}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetAllCities {
    getAllCities{
        id
        name
    }
}

#& ---------------------------- GET ALL RESTAURANT BY CITY
### 
POST {{ endpoint }}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetAllRestaurantByCity($CityId: ID!) {
    getCity(id: $CityId){
        id
        name
        restaurants{
            id
            name
        }
    }
}

{
    "CityId":8
}

#& ---------------------------- ALL COOKING STYLE 
### 
POST {{ endpoint }}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetCookingStyles {
    getCookingStyles{
        label
    }
}

#& ---------------------------- COOKING STYLE BY CITY NAME
### 
POST {{ endpoint }}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetStyleByName($label: String!) {
  getStyleByName(label: $label) {
    label
    id
    restaurants{
      name
      city{
        name
      }
    }
  }
}

{
 "label":"Ukraine"
}

#& ---------------------------- API WEATHER THIRD PARTY
### 
POST {{ endpoint }}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetCity($getCityId: ID!) {
  getCity(id: $getCityId) {
    name
    weather{
        LocalizedName
    }
  }
}

{
  "getCityId": 3
}


### TEST API here

GET https://pokeapi.co/api/v2/pokemon/ditto